### ISSUE TITLE
bot crash 

### ISSUE THREAD

**Issue by ch4oz4ngel** [tama/pogo-discord-raid-bot#3]
the bot crash with following log

(bot-env) root@59997-53573:~/pogo-discord-raid-bot# python3 main.py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    import Player
  File "/root/pogo-discord-raid-bot/Player.py", line 1, in <module>
    from dateutil import parser
  File "/root/pogo-discord-raid-bot/bot-env/lib/python3.7/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

**Comment by tama** [comment]
Hi, thanks for using the bot !

Looking at your stacktrace, it seems like a problem from the dateutil package you're using, make sure it is the correct version (I'm using version 2.8.1 on mine).
If it still does not work, please describe what you're doing and/or provide a way for us to reproduce the bug.

**Comment by ch4oz4ngel** [comment]
the problem with dateutil is solved with a reinstall from the os 
but now i become this 


^C(bot-env) root@59997-53573:~/pogo-discord-raid-bot# python3 main.py
plugin.py
default.py
<class 'default.Default'>
{'default': <class 'default.Default'>}
648220935375290370 b'ch4oz' -> boulbi
Connected !
?
Ignoring exception in on_message
Traceback (most recent call last):
  File "/root/pogo-discord-raid-bot/bot-env/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 178, in on_message
    await process(message)
  File "main.py", line 181, in process
    h = handlers[message.channel.guild.id]
KeyError: 648220935375290370

i make the subfolder in data/{serverid}

**Comment by tama** [comment]
Is your data folder a subfolder of the ~/pogo-discord-raid-bot folder ?
Check the name of the serverid folder inside the data folder and make sure it is exactly the same as the serverid.

**Comment by ch4oz4ngel** [comment]
(bot-env) root@59997-53573:~/pogo-discord-raid-bot# ls
Capture.PNG  Player.py  README.md  __pycache__  _config.yml  bot-env  data  dataAPI  loader.py  main.py  plugins
(bot-env) root@59997-53573:~/pogo-discord-raid-bot# cd data
(bot-env) root@59997-53573:~/pogo-discord-raid-bot/data# ls
648220935375290370  clean.py  whitelist
(bot-env) root@59997-53573:~/pogo-discord-raid-bot/data# cd 648220935375290370/
(bot-env) root@59997-53573:~/pogo-discord-raid-bot/data/648220935375290370# ls
(bot-env) root@59997-53573:~/pogo-discord-raid-bot/data/648220935375290370#

**Comment by ch4oz4ngel** [comment]
Reinstall on home folder i become this





(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# python3 main.py
plugin.py
default.py
<class 'default.Default'>
{'default': <class 'default.Default'>}
Traceback (most recent call last):
  File "main.py", line 826, in <module>
    handlers[int(s)] = plugins[conf[int(s)]["handler"]]()
KeyError: 'boulbi'
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# cd ..
(bot-env) root@59997-53573:/home# cd pogo-discord-raid-bot/
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# ls
Capture.PNG  Player.py  README.md  __pycache__  _config.yml  bot-env  data  dataAPI  loader.py  main.py  plugins
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# cd data
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# ls
322379168048349185  clean.py  whitelist  {648220935375290370}
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# mv \{648220935375290370\}/ 648220935375290370
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# ls
322379168048349185  648220935375290370  clean.py  whitelist
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# cd ..
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# python3 main.py
plugin.py
default.py
<class 'default.Default'>
{'default': <class 'default.Default'>}
Traceback (most recent call last):
  File "main.py", line 826, in <module>
    handlers[int(s)] = plugins[conf[int(s)]["handler"]]()
KeyError: 'boulbi'

**Comment by ch4oz4ngel** [comment]
this is my full install log

root@59997-53573:/home# git clone https://github.com/tama/pogo-discord-raid-bot.git
Cloning into 'pogo-discord-raid-bot'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 55 (delta 0), reused 0 (delta 0), pack-reused 54
Unpacking objects: 100% (55/55), done.
root@59997-53573:/home# ls
pogo-discord-raid-bot
root@59997-53573:/home# cd pogo-discord-raid-bot/
root@59997-53573:/home/pogo-discord-raid-bot# python3 -m pip install -U discord.py
Requirement already up-to-date: discord.py in /usr/local/lib/python3.7/dist-packages (1.3.4)
Requirement already satisfied, skipping upgrade: websockets!=7.0,!=8.0,!=8.0.1,<9.0,>=6.0 in /usr/local/lib/python3.7/dist-packages (from discord.py) (8.1)
Requirement already satisfied, skipping upgrade: aiohttp<3.7.0,>=3.6.0 in /usr/local/lib/python3.7/dist-packages (from discord.py) (3.6.2)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp<3.7.0,>=3.6.0->discord.py) (4.7.6)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<3.7.0,>=3.6.0->discord.py) (19.3.0)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<3.7.0,>=3.6.0->discord.py) (3.0.1)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in /usr/lib/python3/dist-packages (from aiohttp<3.7.0,>=3.6.0->discord.py) (3.0.4)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<3.7.0,>=3.6.0->discord.py) (1.5.1)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.7.4; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from yarl<2.0,>=1.0->aiohttp<3.7.0,>=3.6.0->discord.py) (3.7.4.2)
Requirement already satisfied, skipping upgrade: idna>=2.0 in /usr/local/lib/python3.7/dist-packages (from yarl<2.0,>=1.0->aiohttp<3.7.0,>=3.6.0->discord.py) (2.10)
root@59997-53573:/home/pogo-discord-raid-bot# python3 -m pip install -U discord.py[voice]
Requirement already up-to-date: discord.py[voice] in /usr/local/lib/python3.7/dist-packages (1.3.4)
Requirement already satisfied, skipping upgrade: aiohttp<3.7.0,>=3.6.0 in /usr/local/lib/python3.7/dist-packages (from discord.py[voice]) (3.6.2)
Requirement already satisfied, skipping upgrade: websockets!=7.0,!=8.0,!=8.0.1,<9.0,>=6.0 in /usr/local/lib/python3.7/dist-packages (from discord.py[voice]) (8.1)
Collecting PyNaCl==1.3.0; extra == "voice" (from discord.py[voice])
  Downloading https://files.pythonhosted.org/packages/27/15/2cd0a203f318c2240b42cd9dd13c931ddd61067809fee3479f44f086103e/PyNaCl-1.3.0-cp34-abi3-manylinux1_x86_64.whl (759kB)
    100% |████████████████████████████████| 768kB 1.3MB/s
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp<3.7.0,>=3.6.0->discord.py[voice]) (4.7.6)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<3.7.0,>=3.6.0->discord.py[voice]) (3.0.1)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in /usr/lib/python3/dist-packages (from aiohttp<3.7.0,>=3.6.0->discord.py[voice]) (3.0.4)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<3.7.0,>=3.6.0->discord.py[voice]) (1.5.1)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<3.7.0,>=3.6.0->discord.py[voice]) (19.3.0)
Collecting cffi>=1.4.1 (from PyNaCl==1.3.0; extra == "voice"->discord.py[voice])
  Downloading https://files.pythonhosted.org/packages/d1/fd/10e2050b3afcb03d78b2b33212c3ff17b3985ae25d0feb34c0c9eb417549/cffi-1.14.1-cp37-cp37m-manylinux1_x86_64.whl (401kB)
    100% |████████████████████████████████| 409kB 3.3MB/s
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from PyNaCl==1.3.0; extra == "voice"->discord.py[voice]) (1.12.0)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.7.4; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from yarl<2.0,>=1.0->aiohttp<3.7.0,>=3.6.0->discord.py[voice]) (3.7.4.2)
Requirement already satisfied, skipping upgrade: idna>=2.0 in /usr/local/lib/python3.7/dist-packages (from yarl<2.0,>=1.0->aiohttp<3.7.0,>=3.6.0->discord.py[voice]) (2.10)
Collecting pycparser (from cffi>=1.4.1->PyNaCl==1.3.0; extra == "voice"->discord.py[voice])
  Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
    100% |████████████████████████████████| 112kB 7.1MB/s
Installing collected packages: pycparser, cffi, PyNaCl
Successfully installed PyNaCl-1.3.0 cffi-1.14.1 pycparser-2.20
root@59997-53573:/home/pogo-discord-raid-bot# apt install libffi-dev libnacl-dev python3-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-dev is already the newest version (3.7.3-1).
python3-dev set to manually installed.
The following NEW packages will be installed:
  libffi-dev libnacl-dev
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 222 kB of archives.
After this operation, 971 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://ftp.debian.org/debian buster/main amd64 libffi-dev amd64 3.2.1-9 [156 kB]
Get:2 http://ftp.debian.org/debian buster/main amd64 libnacl-dev amd64 20110221-6.1 [65.9 kB]
Fetched 222 kB in 0s (2404 kB/s)
Selecting previously unselected package libffi-dev:amd64.
(Reading database ... 36832 files and directories currently installed.)
Preparing to unpack .../libffi-dev_3.2.1-9_amd64.deb ...
Unpacking libffi-dev:amd64 (3.2.1-9) ...
Selecting previously unselected package libnacl-dev.
Preparing to unpack .../libnacl-dev_20110221-6.1_amd64.deb ...
Unpacking libnacl-dev (20110221-6.1) ...
Setting up libnacl-dev (20110221-6.1) ...
Setting up libffi-dev:amd64 (3.2.1-9) ...
Processing triggers for install-info (6.5.0.dfsg.1-4+b1) ...
Processing triggers for man-db (2.8.5-2) ...
root@59997-53573:/home/pogo-discord-raid-bot# python3 -m venv bot-env
root@59997-53573:/home/pogo-discord-raid-bot# source bot-env/bin/activate
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# pip install -U discord.py
Collecting discord.py
  Using cached https://files.pythonhosted.org/packages/e9/d4/1b6e6ed08d9cfb6b31ae6eae7cbb57373c153e9f1a7037b369579dccb0b2/discord.py-1.3.4-py3-none-any.whl
Collecting websockets!=7.0,!=8.0,!=8.0.1,<9.0,>=6.0 (from discord.py)
  Using cached https://files.pythonhosted.org/packages/df/19/2573653fb823929324667c936541be610869b2b389eb9dabfe8c874ea80f/websockets-8.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting aiohttp<3.7.0,>=3.6.0 (from discord.py)
  Using cached https://files.pythonhosted.org/packages/e3/71/6000eacb8923d9fd07aa8784a8fab4f022ae697f3c2456d7dca75c743dd6/aiohttp-3.6.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting async-timeout<4.0,>=3.0 (from aiohttp<3.7.0,>=3.6.0->discord.py)
  Using cached https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting attrs>=17.3.0 (from aiohttp<3.7.0,>=3.6.0->discord.py)
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting chardet<4.0,>=2.0 (from aiohttp<3.7.0,>=3.6.0->discord.py)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting multidict<5.0,>=4.5 (from aiohttp<3.7.0,>=3.6.0->discord.py)
  Using cached https://files.pythonhosted.org/packages/85/b8/a9fe777dab4c6aa067b516a34fe995213707e490ea1e72f823949a830a6a/multidict-4.7.6-cp37-cp37m-manylinux1_x86_64.whl
Collecting yarl<2.0,>=1.0 (from aiohttp<3.7.0,>=3.6.0->discord.py)
  Using cached https://files.pythonhosted.org/packages/5b/1c/556b99a3a11916e05cd2128367f507dc330fc30ed1f5991e1ffe4dabf635/yarl-1.5.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting typing-extensions>=3.7.4; python_version < "3.8" (from yarl<2.0,>=1.0->aiohttp<3.7.0,>=3.6.0->discord.py)
  Using cached https://files.pythonhosted.org/packages/0c/0e/3f026d0645d699e7320b59952146d56ad7c374e9cd72cd16e7c74e657a0f/typing_extensions-3.7.4.2-py3-none-any.whl
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp<3.7.0,>=3.6.0->discord.py)
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Installing collected packages: websockets, async-timeout, attrs, chardet, multidict, typing-extensions, idna, yarl, aiohttp, discord.py
Successfully installed aiohttp-3.6.2 async-timeout-3.0.1 attrs-19.3.0 chardet-3.0.4 discord.py-1.3.4 idna-2.10 multidict-4.7.6 typing-extensions-3.7.4.2 websockets-8.1 yarl-1.5.1
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# ls
Capture.PNG  Player.py  README.md  _config.yml  bot-env  data  dataAPI  loader.py  main.py  plugins
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# cd data
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# mkdir {648220935375290370}
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# cd ..
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# nano .token
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# (bot-env) root@59997-53573:/home/pogo-discord-raid-bot# mpython3 main.py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    import Player
  File "/home/pogo-discord-raid-bot/Player.py", line 1, in <module>
    from dateutil import parser
ModuleNotFoundError: No module named 'dateutil'
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# pip install dateutil
Collecting dateutil
  Could not find a version that satisfies the requirement dateutil (from versions: )
No matching distribution found for dateutil
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# pip install python-dateutil==2.8.1
Collecting python-dateutil==2.8.1
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil==2.8.1)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil
Successfully installed python-dateutil-2.8.1 six-1.15.0
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# python3 main.py
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    import geopy.distance
ModuleNotFoundError: No module named 'geopy'
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# pip install geopy
Collecting geopy
  Using cached https://files.pythonhosted.org/packages/07/e1/9c72de674d5c2b8fcb0738a5ceeb5424941fefa080bfe4e240d0bacb5a38/geopy-2.0.0-py3-none-any.whl
Collecting geographiclib<2,>=1.49 (from geopy)
  Using cached https://files.pythonhosted.org/packages/8b/62/26ec95a98ba64299163199e95ad1b0e34ad3f4e176e221c40245f211e425/geographiclib-1.50-py3-none-any.whl
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-1.50 geopy-2.0.0
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# python3 main.py
plugin.py
default.py
<class 'default.Default'>
{'default': <class 'default.Default'>}
Traceback (most recent call last):
  File "main.py", line 826, in <module>
    handlers[int(s)] = plugins[conf[int(s)]["handler"]]()
KeyError: 'boulbi'
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# cd ..
(bot-env) root@59997-53573:/home# cd pogo-discord-raid-bot/
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# ls
Capture.PNG  Player.py  README.md  __pycache__  _config.yml  bot-env  data  dataAPI  loader.py  main.py  plugins
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# cd data
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# ls
322379168048349185  clean.py  whitelist  {648220935375290370}
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# mv \{648220935375290370\}/ 648220935375290370
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# ls
322379168048349185  648220935375290370  clean.py  whitelist
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# cd ..
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# python3 main.py
plugin.py
default.py
<class 'default.Default'>
{'default': <class 'default.Default'>}
Traceback (most recent call last):
  File "main.py", line 826, in <module>
    handlers[int(s)] = plugins[conf[int(s)]["handler"]]()
KeyError: 'boulbi'

**Comment by tama** [comment]
> Reinstall on home folder i become this
> 
> (bot-env) root@59997-53573:/home/pogo-discord-raid-bot# python3 main.py
> plugin.py
> default.py
> <class 'default.Default'>
> {'default': <class 'default.Default'>}
> Traceback (most recent call last):
> File "main.py", line 826, in
> handlers[int(s)] = pluginsconf[int(s)]["handler"]
> KeyError: 'boulbi'
> (bot-env) root@59997-53573:/home/pogo-discord-raid-bot# cd ..
> (bot-env) root@59997-53573:/home# cd pogo-discord-raid-bot/
> (bot-env) root@59997-53573:/home/pogo-discord-raid-bot# ls
> Capture.PNG Player.py README.md **pycache** _config.yml bot-env data dataAPI loader.py main.py plugins
> (bot-env) root@59997-53573:/home/pogo-discord-raid-bot# cd data
> (bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# ls
> 322379168048349185 clean.py whitelist {648220935375290370}
> (bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# mv {648220935375290370}/ 648220935375290370
> (bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# ls
> 322379168048349185 648220935375290370 clean.py whitelist
> (bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# cd ..
> (bot-env) root@59997-53573:/home/pogo-discord-raid-bot# python3 main.py
> plugin.py
> default.py
> <class 'default.Default'>
> {'default': <class 'default.Default'>}
> Traceback (most recent call last):
> File "main.py", line 826, in
> handlers[int(s)] = pluginsconf[int(s)]["handler"]
> KeyError: 'boulbi'

The "boulbi" shouldn't be here, try to edit the "conf" file inside your data/{serverid} folder, and remove the last line "handler:boulbi" inside it

**Comment by ch4oz4ngel** [comment]
there is nothing in the folder

**Comment by tama** [comment]
Ok, then delete the 32237916.... folder inside your data folder, that's the "sample" one it's not working.

EDIT :
(bot-env) root@59997-53573:/home/pogo-discord-raid-bot/data# ls
**322379168048349185** <- this one  648220935375290370 clean.py whitelist

**Comment by ch4oz4ngel** [comment]
nice he start and dont crash
only the commands doesnt work but i think i can handle this

**Comment by ch4oz4ngel** [comment]
thx for the help

**Comment by tama** [comment]
You're welcome.
Feel free to open an issue if you can't solve the commands problem.
